//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _312
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Information_Depatment = new HashSet<Information_Depatment>();
            this.Tehnical_Depatment = new HashSet<Tehnical_Depatment>();
        }
    
        public int Id_Treaty { get; set; }
        public int Id_Company { get; set; }
        public Nullable<int> Id_Customers { get; set; }
        public int Id_Services { get; set; }
        public int Id_Department { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> C_End { get; set; }
        public int Price { get; set; }
        public Nullable<int> Id_CustomersYR_L { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customers_F_L Customers_F_L { get; set; }
        public virtual Customers_YR_L Customers_YR_L { get; set; }
        public virtual Price_Services Price_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Information_Depatment> Information_Depatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tehnical_Depatment> Tehnical_Depatment { get; set; }
    }
}
