//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _312
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STU_PROJECTEntities : DbContext
    {
        public STU_PROJECTEntities()
            : base("name=STU_PROJECTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Customers_F_L> Customers_F_L { get; set; }
        public virtual DbSet<Customers_YR_L> Customers_YR_L { get; set; }
        public virtual DbSet<Developers> Developers { get; set; }
        public virtual DbSet<Information_Depatment> Information_Depatment { get; set; }
        public virtual DbSet<Price_Services> Price_Services { get; set; }
        public virtual DbSet<Tehnical_Depatment> Tehnical_Depatment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
