//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _312
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tehnical_Depatment
    {
        public int Id_Empioyee { get; set; }
        public int Id_Contract { get; set; }
        public int Work_Process { get; set; }
        public int Id_Department { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Developers Developers { get; set; }
    }
}
